### PR TITLE
Added favicon method to CanvasMacros

### PR DESCRIPTION
**Pull request by petermost**

### CODE REVIEW

**Comment by petermost** [comment]
Sorry, the project file was not intended for this pull request.

**Comment by petermost** [comment]
Sorry closed this pull request by accident.

**Comment by petermost** [comment]
Is there something missing from me so you can't merge these changes?

**Comment by emicklei** [comment]
again, thank you for your contributions.

On Tue, Feb 3, 2015 at 10:03 PM, Peter Most <notifications@github.com>
wrote:

> Is there something missing from me so you can't merge these changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emicklei/rendersnake/pull/2#issuecomment-72734143>.
>



-- 
^ Ernest Micklei

http://ernestmicklei.com

**Pull request merged**
